### ISSUE TITLE
TypeScript issue when defining columns

### ISSUE THREAD

**Issue by danielimmke** [bryanmylee/svelte-headless-table#106]
Thanks for creating this, it's really useful. I get a persistent issue with TS where it doesn't like the `accessor` property. Even though the docs say that is actually what is required.

Here's a screenshot of the problem. I did find the accessor property in your typing, but it's so complex it was really hard for me to follow.

I think it would be nice if we could just pass an array of regular objects into `createColumns` instead of having to wrap them in `column`.
![error](https://user-images.githubusercontent.com/1744366/217925359-5e86b5f6-bdd8-41ba-8b2f-ffdb6cbd02e9.png)
![column-type-definition](https://user-images.githubusercontent.com/1744366/217925322-7a6eaafc-ba80-4865-85be-506bfd048bfc.png)

**Comment by danielimmke** [comment]
As a side note, making accessor a function that returned a string made this error go away. I think it's actually trying to verify if the accessor is in the data and it hadn't updated when I switched data or something.

**Comment by bryanmylee** [comment]
Hey @danielimmke, can I check what the type is for `dataSet`? The type for `accessor` depends on the properties defined on each item in your data store.

I think that's a general issue with TypeScript unfortunately. It's often more difficult to read than write, and there's a lot of complexity required to support well-defined types.

My initial design did allow an array of regular objects, but that caused even more issues due to generic type inference and created an even more complicated type for `createColumns`.

**Comment by bryanmylee** [comment]
> As a side note, making accessor a function that returned a string made this error go away. I think it's actually trying to verify if the accessor is in the data and it hadn't updated when I switched data or something.

When `accessor` is a function, it allows you to return any value from each item because it assumes you'd be deriving an arbitrary value from each item, e.g:

```ts
const data = writable<Item[]>([
  {firstName: "Bryan", username: "bryanmylee"},
  {firstName: "Daniel", username: "danielimmke"},
]);

// ...
const columns = createColumns([
  column({
    header: "Title",
    // could be any value
    accessor: (item) => item.firstName + " @" + item.username,
  }),
  column({
    header: "Name length",
    // could be any value
    accessor: (item) => item.firstName.length,
  }),
  column({
    header: "Name",
    // has to be either "firstName" or "username", derived 
    // from `keyof Item`
    accessor: "firstName",
  }),
])
```

My guess is that `item` is being typed as `unknown` or `any` due to a lack of types on `dataSet`.

**Comment by danielimmke** [comment]
I see. That's kind of what I was thinking. Thanks for the reply and again for making the library.

As a side note, I have worked with this library a lot and have built some stuff that isn't on your demo site. I try to contribute back to projects I use when I can. Would you be interested in a demo with pagination?

I custom wrote the logic for how it renders the paging area so it could be a good thing for people to look at (or copy/paste 😛)

**Comment by bryanmylee** [comment]
I'd love to have your contributions! Although the demo site is currently in limbo due to breaking changes between SvelteKit and the documentation plugin I'm using.

Long story short I can't publish new changes to the site because Vercel removed a certain deployment method that SvelteKit beta relied on, but the documentation plugin I'm not relies on SvelteKit beta 😞

**Comment by danielimmke** [comment]
Ok I will open a separate issue for this.
