### ISSUE TITLE
Use `createRender` for native elements with arbitrary attributes

### ISSUE THREAD

**Issue by lulucas** [bryanmylee/svelte-headless-table#34]
Just something like ,
```
createRender('div', {class: 'i-ic:iconname' })
```

render div with classname like <svelte:element this="div"> do.

**Comment by bryanmylee** [comment]
I'll take a look into extending the `createRender` paradigm!

This should line up pretty well with Svelte's `<svelte:element>` tag anyways.

**Comment by bryanmylee** [comment]
@lulucas After some consideration, I feel that it's not really intuitive to create native elements with `createRender`, solely because it feels like I'm trying to re-implement HTML and templating in JS.

If I implement something like `createRender('div', {class: 'i-ic:iconname' })`, then it's odd not to also provide some support for children elements etc., which feels like re-implementing JSX or other templating engines.

The best bet for your use case would be to define a simple Svelte component that does what you need i.e.

```svelte
<!-- Icon.svelte -->
<script lang="ts">
  export let name: string;
</script>
<div class={name} />
```

```svelte
<!-- index.svelte -->
<script lang="ts">
  import Icon from './Icon.svelte';
  ...
  createRender(Icon, { icon: 'i-ic:iconname' });
</script>
```
