### ISSUE TITLE
Discussion on how to implement editable table

### ISSUE THREAD

**Issue by Mattchine** [bryanmylee/svelte-headless-table#35]
I just tried and fall in love with this library, thanks a lot.

I want suggestion or to discuss on how to implement `editable-table` better.

This is my [REPL implementation](https://svelte.dev/repl/ab5be587a0ab41d79dfeb2f8123a1ddc?version=3.49.0), which feel like a hacky way.

1. `store` (`Writable`) is in its own file and is imported by `Table` and `Input` component
2. `Input` has 3 props: `value`, `rowId` and `columnId`
3. `cell` use `createRender` to render `Input` and pass all `props` to `Input` component
4. `Input` component then access `store` with `$store` and set value with `$store[rowId][columnId] = value`
___
Edit:
Current problem
- No type definition for `row` and `column` to use in `Input` component
- I'm not sure about accessing store value with `$store[rowId][columnId]` is the best way or should there be an alternative way.

**Comment by Mattchine** [comment]
[Related issue](https://github.com/bryanmylee/svelte-headless-table/issues/17)

**Comment by bryanmylee** [comment]
I'm glad you're enjoying the library @Mattchine! Perhaps I should create some examples on the documentation site to show how I envisioned data editing would look like.

I wanted `$data` to be the source of truth for the table, and since most data sources are usually synced with some server-side data, I figured it wouldn't make sense to create the `addEditable` plugin.

As you've noticed, each `DataBodyRow` comes with a `dataId` that is tied to the original ID of the data item. The goal was to let the user dispatch "updates" from their `EditableCell` / `Input` component, then update `$data` by searching for that `dataId`.

I'll update you again when I have an example set up!

**Comment by rohanrajpal** [comment]
> I'm glad you're enjoying the library @Mattchine! Perhaps I should create some examples on the documentation site to show how I envisioned data editing would look like.
> 
> I wanted `$data` to be the source of truth for the table, and since most data sources are usually synced with some server-side data, I figured it wouldn't make sense to create the `addEditable` plugin.
> 
> As you've noticed, each `DataBodyRow` comes with a `dataId` that is tied to the original ID of the data item. The goal was to let the user dispatch "updates" from their `EditableCell` / `Input` component, then update `$data` by searching for that `dataId`.
> 
> I'll update you again when I have an example set up!

@bryanmylee I've been also trying to make an editable table and your points are super helpful. Will be waiting for the example when it's out.

Thanks a ton for this useful library!

**Comment by bryanmylee** [comment]
@rohanrajpal @Mattchine 

I've updated the documentation to include an editable table example:
https://svelte-headless-table.bryanmylee.com/docs/examples/editable-table
