### ISSUE TITLE
Why use "header" and "Render" in column definition at all ?

### ISSUE THREAD

**Issue by FluffyDiscord** [bryanmylee/svelte-headless-table#49]
First of all - I am probably doing this the wrong way, so please enlighten me.

I would like to have custom header cell, so I guess I have three ways to do it
```svelte
{#each headerRow.cells as cell (cell.id)}
    <Subscribe attrs={cell.attrs()} props={cell.props()} let:attrs let:props>
        <div {...attrs}>
             // render my custom component like this
            <Render of={cell.render()}/>

            // or  just use plain html
            <span>{cell.label}</span>

            // or svelte component
            <MyCustomHeader {cell}/>
        </div>
    </Subscribe>
{/each}
```

Looking at the docs, you are recommending to use `createRender` tho. Why is `Render` recommended ? If we want to enable the sorting plugin, we are adding plain html anyway, right ?

```svelte
{#each headerRow.cells as cell (cell.id)}
    <Subscribe attrs={cell.attrs()} props={cell.props()} let:attrs let:props>
        <div {...attrs}>
            <Render of={cell.render()}/>

            // from the example
            {#if props.sort.order === 'asc'}
                ⬇️
            {:else if props.sort.order === 'desc'}
                ⬆️
             {/if}
        </div>
    </Subscribe>
{/each}
```

If I want to have that sorting "hidden" in the header cell component, I need to do this kind of thing, since `header` does not provide the specific `HeaderCell` but the whole table state.

```ts
table.column({
    header: (state) => {
        return createRender(TableHeaderCell, {
            label: "Popis",
            sortToggle: () => state.pluginStates.sort.sortKeys.toggleId("description", {}),
            sortOrder: get(state.pluginStates.sort.sortKeys).find(key => key.id === "description")?.order
        })
    },
    accessor: "description",
}),
```

I feel like I am doing something horribly wrong. Would you mind explaining please ?

**Comment by bryanmylee** [comment]
Hi @FluffyDiscord, thanks for highlighting this!

The principle I aimed for with this library is flexibility, however I admit that this makes things more complicated and probably more confusing that it has to be.

To answer your question directly, in the examples, I rendered the sorting indicator on the template instead of the column definitions because:
1. the sorting indicator is an element that should appear on all columns whereas the `header` definition on the columns are a per-column definition; and
2. it is more straightforward for the purpose of a short code demo.

In the long run, you're right that we should be defining all the logic in `createRender`. **It was an oversight on my part not to include the column, row, and header cell of the header in the `header` definition**, and I'm definitely not happy with the API right now.

I will probably release a breaking change that addresses that issue such that the first argument to `header` is the header cell itself.

**Comment by bryanmylee** [comment]
Hi @FluffyDiscord, you can refer to the updated [documentation](https://svelte-headless-table.bryanmylee.com/docs/api/create-columns#columndef-header-renderconfig-headercell-state-renderconfig) for the updated API.

Let me know if this solves your use case!

**Comment by FluffyDiscord** [comment]
@bryanmylee more than solves, thank you very much !
