### ISSUE TITLE
reactive header?

### ISSUE THREAD

**Issue by thomas725** [bryanmylee/svelte-headless-table#75]
Hi there!

I'm trying to use this component in an app of mine.

It's using `svelte-i18n`, and for a vanilla table I put stuff like: `<th>{$_('name')}</th>` into the svelte template section for my table headers. This automatically changes when the language is switched.

Now to get started with your library, I've copied the code from your [quick-start sample](https://svelte-headless-table.bryanmylee.com/docs/getting-started/quick-start) into a new Svelte component, and added those imports:
```
import { _ } from "svelte-i18n";
import {createTable, Subscribe, Render} from 'svelte-headless-table';
import { readable } from "svelte/store";
```
(it would be nice if you could copy the ones everybody needs into your sample, so future users don't need to search for them themselves, see [pull request](https://github.com/bryanmylee/svelte-headless-table/pull/76))

Anyway, now in the column definition, I replaced `header: 'name'` with `header: $_('name')` - which works, but isn't reactive, so doesn't change when the language changes.

How can I go about doing this in a way that preserves / propagates the reactivity?

**Comment by thomas725** [comment]
Those missing imports in all the sample code in your documentation makes it really hard for a svelte novice like me to try those samples. How to find out which libraries those objects should come from?..

**Comment by bryanmylee** [comment]
Hey @thomas725, thanks for the suggestion. I’ll re-work the examples to make referencing easier, but I’m hesitant to add all imports because I want the examples to be focused.

As for reactivity, you can pass a [readable store directly](https://svelte-headless-table.bryanmylee.com/docs/api/create-columns#columndef-header-renderconfig-headercell-state-renderconfig) instead of its subscribed value as the header to make it reactive, as the header prop accepts what I call a [`RenderConfig`](https://svelte-headless-table.bryanmylee.com/docs/api/--render#renderconfig).

```ts
import { _ } from "svelte-i18n";
import {createTable, Subscribe, Render} from 'svelte-headless-table';
import { readable } from "svelte/store";

const table = createTable(data);
const columns = table.createColumns([
  {
    header: _('name'), // note the missing $
    ...
  }
]);
```

**Comment by thomas725** [comment]
Thank you for your reply, and thanks for considering my suggestion about the imports.

The suggested syntax, leaving out the '$' sign before `_('name')` gives me this compiler error:
```
This expression is not callable.
  Type 'Readable<MessageFormatter>' has no call signatures.
```

**Comment by bryanmylee** [comment]
Ah I see, I think the issue is that `_` returned from `svelte-i18n` is a store and not a store getter i.e. `$_('name')` is accessing the store value `$_` which returns a function, then calling it with `'name'`. I mistook the syntax as `_('name')` being a store which is then accessed with `$`.

To resolve your issue, you have to use a derived store instead.

```
import {_} from "svelte-i18n";
import {createTable, Subscribe, Render} from 'svelte-headless-table';
import {readable, derived} from "svelte/store";

const table = createTable(data);
const columns = table.createColumns([
  {
    header: derived(_, $_ => $_('name')),
    ...
  }
]);
```
